from __future__ import annotations
from dataclasses import dataclass
import math
from packages.economics.singapore_costs import buyer_stamp_duty,land_betterment_charge
@dataclass
class EnBlocInputs:
 current_strata_value_m:float;site_area_sqm:float;existing_gfa_sqm:float;legal_gpr:float;nla_efficiency:float;sale_price_per_nla_sqm:float;construction_cost_per_gfa_sqm:float;lbc_rate_per_sqm:float|None;tenure_remaining_years:float|None;owners_count:int;required_consent:float=.8;professional_rate:float=.12;finance_rate:float=.08;marketing_rate:float=.025;demolition_m:float=2;tenant_cost_m:float=0;developer_margin_rate:float=.2;failed_attempts:int=0;timeline_years:float=3
def evaluate_enbloc(x:EnBlocInputs):
 allowable=x.site_area_sqm*x.legal_gpr;additional=max(0,allowable-x.existing_gfa_sqm);nla=allowable*x.nla_efficiency;gdv=nla*x.sale_price_per_nla_sqm/1e6;construction=allowable*x.construction_cost_per_gfa_sqm/1e6;professional=construction*x.professional_rate;finance=(construction+professional)*x.finance_rate;marketing=gdv*x.marketing_rate;lbc=land_betterment_charge(additional,x.lbc_rate_per_sqm);lbc_m=lbc['total_sgd']/1e6 if lbc.get('total_sgd') is not None else 0;developer_margin=gdv*x.developer_margin_rate;bsd=buyer_stamp_duty(x.current_strata_value_m*1e6,1)['total_sgd']/1e6;max_land=gdv-construction-professional-finance-marketing-lbc_m-developer_margin-x.demolition_m-x.tenant_cost_m-bsd;premium=(max_land/x.current_strata_value_m-1) if x.current_strata_value_m else 0;tenure_factor=1 if x.tenure_remaining_years is None else min(1,max(.25,x.tenure_remaining_years/99));fragmentation=max(0,math.log(max(x.owners_count,1))/math.log(500));logit=-1.7+5*max(0,premium)+1.2*tenure_factor-1.1*fragmentation-.65*x.failed_attempts;consent=1/(1+math.exp(-logit));success=max(0,min(1,consent*(1 if max_land>0 else .15)));discounted=max(0,max_land)/(1.078**x.timeline_years)*success;return {'allowable_gfa_sqm':round(allowable,2),'additional_gfa_sqm':round(additional,2),'gross_development_value_m':round(gdv,3),'construction_m':round(construction,3),'professional_m':round(professional,3),'finance_m':round(finance,3),'marketing_m':round(marketing,3),'lbc':lbc,'developer_margin_m':round(developer_margin,3),'buyer_stamp_duty_m':round(bsd,3),'maximum_land_value_m':round(max_land,3),'premium_over_current_value':round(premium,4),'owner_consent_probability':round(consent,4),'success_probability':round(success,4),'expected_discounted_enbloc_value_m':round(discounted,3),'timeline_years':x.timeline_years,'verification_required':lbc['status']!='calculated'}
