import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Search } from 'lucide-react';
import { DigitalTwinCharts } from './Visuals';
const money = (value: any) => typeof value === 'number' && Number.isFinite(value) ? `S$${value.toFixed(2)}m` : 'Unavailable';
const pct = (value: any) => typeof value === 'number' && Number.isFinite(value) ? `${(value * 100).toFixed(1)}%` : 'Unavailable';
function Card({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="metric"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>; }
export default function DigitalTwinDashboard({ api, staticMode = false }: { api: string; staticMode?: boolean }) {
  const [data, setData] = useState<any>(), [environmentId, setEnvironmentId] = useState('base'), [search, setSearch] = useState(''), [action, setAction] = useState('All'), [error, setError] = useState('');
  useEffect(() => {
    const controller = new AbortController(); setData(undefined); setError('');
    fetch(staticMode ? import.meta.env.BASE_URL + 'data/digital_twin_dashboard.json' : api + '/digital-twins/dashboard', { signal: controller.signal })
      .then(response => { if (!response.ok) throw new Error('Digital-twin results are unavailable.'); return response.json(); })
      .then(setData).catch(reason => { if (reason.name !== 'AbortError') setError(reason.message); });
    return () => controller.abort();
  }, [api, staticMode]);
  const environment = data?.environments?.find((row: any) => row.id === environmentId);
  const filtered = useMemo(() => (data?.assets || []).filter((row: any) => {
    const matches = !search || `${row.name} ${row.asset_id} ${row.segment} ${row.planning_area}`.toLowerCase().includes(search.toLowerCase());
    return matches && (action === 'All' || row.environments?.[environmentId]?.recommended_action === action);
  }), [data, environmentId, search, action]);
  if (error) return <div className="alert alert-danger" role="alert">{error}</div>;
  if (!data) return <p>Loading digital twins…</p>;
  if (data.status === 'not_run' || !environment) return <div className="warning">Digital-twin results have not been published yet.</div>;
  const portfolio = environment.portfolio || {}, summary = data.portfolio_summary || {}, method = data.methodology || {};
  const contextMean = filtered.length ? filtered.reduce((sum: number, row: any) => sum + (row.context_completeness_pct ?? row.real_context_pct ?? 0), 0) / filtered.length : null;
  const verifiedMean = filtered.length ? filtered.reduce((sum: number, row: any) => sum + (row.verified_underwriting_pct ?? 0), 0) / filtered.length : null;
  const selectionById = new Map((portfolio.selections || []).map((row: any) => [row.asset_id, row]));
  return <div className="digital-twin-page">
    <div className="alert alert-warning d-flex align-items-start" role="alert"><AlertTriangle className="me-2 flex-shrink-0" size={20}/><div><strong>Synthetic decision experiment</strong><p className="mb-0">Financial histories, leases and simulated outcomes are generated. {summary.fictional_asset_contexts ?? 'The public'} asset contexts are fictional. Populated fields do not imply verification. No observed investment performance or demonstrated alpha is established.</p></div></div>
    <section><h2>Environment and asset filters</h2><div className="btn-list mb-3">{data.environments.map((row: any) => <button key={row.id} className={`btn ${environmentId === row.id ? 'btn-primary' : 'btn-outline-secondary'}`} aria-pressed={environmentId === row.id} onClick={() => setEnvironmentId(row.id)}>{row.label}</button>)}</div><div className="filters"><label><Search size={17}/><input aria-label="Search digital twins" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search asset, segment or area"/></label><select aria-label="Digital twin recommendation filter" value={action} onChange={event => setAction(event.target.value)}>{['All', 'Hold', 'Retrofit', 'Repurpose', 'Redevelop', 'Sell'].map(value => <option key={value}>{value}</option>)}</select></div><p>Cards, asset charts and the decision table reflect these filters. The full portfolio optimisation is shown separately below.</p></section>
    <div className="metrics"><Card label="Displayed twins" value={String(filtered.length)} detail={`${data.assets?.length || 0} total assets`}/><Card label="Context completeness" value={pct(contextMean)} detail="Populated fields; not verified coverage"/><Card label="Verified underwriting" value={pct(verifiedMean)} detail="Generated financials are not evidence"/><Card label="Changing decisions" value={String(filtered.filter((row: any) => row.fragile).length)} detail="Action differs across environments"/></div>
    <DigitalTwinCharts data={data} assets={filtered} environmentId={environmentId}/>
    <section><h2>Filtered asset decisions · {environment.label}</h2><p>Independent preferred actions can differ from the full portfolio allocation because of capital, income, concurrency and joint risk constraints. Intervals describe incremental NPV versus Hold; zero Hold risk does not mean the property itself has no risk.</p><div className="tablewrap"><table><thead><tr><th>Asset</th><th>Segment</th><th>Preferred action</th><th>Portfolio action / start</th><th>Expected NPV</th><th>P10–P90</th><th>Loss probability</th><th>Scenario agreement</th><th>Evidence</th></tr></thead><tbody>{filtered.map((row: any) => {
      const result = row.environments?.[environmentId] || {}, selected: any = selectionById.get(row.asset_id);
      return <tr key={row.asset_id}><td><b>{row.name}</b><small>{row.asset_id} · {row.planning_area}</small></td><td>{row.segment}</td><td>{result.recommended_action}</td><td>{selected ? `${selected.action} / year ${selected.start_year}` : 'Unavailable'}</td><td>{money(result.expected_npv_m)}</td><td>{money(result.p10_m)} to {money(result.p90_m)}</td><td>{pct(result.probability_of_loss)}</td><td>{pct(row.stability_score)}<small>{row.fragile ? 'Action changes' : 'Same action'}</small></td><td>{row.context_status === 'synthetic_fixture' ? 'Fictional context' : 'Supplied context'}<small>Synthetic financials</small></td></tr>;
    })}</tbody></table>{!filtered.length && <p>No assets match these filters.</p>}</div></section>
    <section><h2>Full portfolio allocation · {environment.label}</h2><p>{environment.description} This section always represents all {summary.assets} assets; search and recommendation filters do not rerun the optimiser.</p><div className="metrics"><Card label="Expected portfolio NPV" value={money(portfolio.portfolio_expected_npv_m)} detail="Decision-time incremental value"/><Card label="Penalised objective" value={money(portfolio.portfolio_risk_adjusted_objective_m)} detail="Expected NPV minus joint loss-risk penalty"/><Card label="Joint loss CVaR 95%" value={money(portfolio.portfolio_cvar_95_m ?? portfolio.portfolio_loss_cvar_m)} detail={`${method.optimisation_scenario_count || 'Aligned'} optimisation scenarios`}/><Card label="Simulated realised NPV" value={money(portfolio.portfolio_simulated_realised_npv_m)} detail="One independent generated outcome; not realised profit"/></div><p>{portfolio.risk_interpretation} Constraint audit: {portfolio.constraint_audit?.passed ? 'passed' : 'unavailable or failed'}; violations {portfolio.constraint_violations ?? 'unavailable'}.</p><div className="tablewrap"><table><thead><tr><th>Year</th><th>Capex</th><th>Sale receipts</th><th>Remaining liquidity</th><th>NOI loss</th><th>Projects</th></tr></thead><tbody>{(portfolio.annual_plan || []).map((row: any) => <tr key={row.year}><td>{row.year}</td><td>{money(row.capex_m)}</td><td>{money(row.capital_released_m)}</td><td>{money(row.remaining_liquidity_m)}</td><td>{money(row.noi_disruption_m)}</td><td>{row.active_projects}</td></tr>)}</tbody></table></div><p>Sale receipts release capital; they are not profit. The liquidity screen uses annual buckets and assumes within-year netting.</p></section>
    <section><h2>Assumptions and simulation diagnostics</h2><div className="facts"><Card label="Rent level change" value={pct(environment.assumptions?.rent_change)} detail="Segment demand shifts also apply"/><Card label="Cap-rate shift" value={pct(environment.assumptions?.cap_rate_shift)} detail="Percentage-point level shift"/><Card label="Construction multiplier" value={String(environment.assumptions?.construction_cost_multiplier ?? 'Unavailable')} detail="Applied to development costs"/><Card label="Approval multiplier" value={String(environment.assumptions?.approval_multiplier ?? 'Unavailable')} detail="Changes approval branch probabilities"/></div><p>Action match to simulation oracle: {pct(environment.correct_action_rate_vs_simulation)}. Mean simulated regret: {money(environment.mean_decision_regret_m)}. P10–P90 interval coverage: {pct(environment.p10_p90_coverage)} across action outcomes, with nominal 80% coverage. These are generator diagnostics, not a historical backtest.</p><p>{method.predictive_scenario_count || 'Modelled'} predictive scenarios; {method.optimisation_scenario_count || 'aligned'} optimisation scenarios. {method.risk_source}. {method.evaluation_source}. Calibration: {method.calibration_status || 'assumption based'}.</p></section>
  </div>;
}
