import { lazy, Suspense, useEffect, useState } from 'react';
import { PUBLIC_DEMO } from '../config';
const Plot = lazy(() => import('./PlotlyChart'));
const COLORS = ['#0f62fe', '#009d9a', '#8a3ffc', '#ff832b', '#da1e28', '#007d79'];
const isNumber = (value: any) => typeof value === 'number' && Number.isFinite(value);
function Chart({ label, title, data, layout = {} }: { label: string; title: string; data: any[]; layout?: any }) {
  return <Suspense fallback={<div className="chart-loading">Loading visualisation…</div>}><Plot ariaLabel={label} data={data} layout={{ title, ...layout }}/></Suspense>;
}
function useData(url: string) {
  const [data, setData] = useState<any>(), [error, setError] = useState('');
  useEffect(() => {
    const controller = new AbortController(); setData(undefined); setError('');
    fetch(url, { signal: controller.signal }).then(response => { if (!response.ok) throw new Error('Data unavailable'); return response.json(); }).then(setData).catch(reason => { if (reason.name !== 'AbortError') setError(reason.message); });
    return () => controller.abort();
  }, [url]);
  return { data, error };
}
function counts(rows: any[], key: (row: any) => string) { const result: Record<string, number> = {}; rows.forEach(row => { const value = key(row); result[value] = (result[value] || 0) + 1; }); return result; }

export function PortfolioCharts({ assets }: { assets: any[] }) {
  const action = counts(assets, row => row.selection?.preferred_action || row.recommendation?.action || 'Not modelled');
  const signals = counts(assets, row => row.selection?.signal || 'Not modelled');
  const segments = counts(assets, row => row.segments?.[0] || 'Unknown');
  const mapped = assets.filter(row => isNumber(row.latitude) && isNumber(row.longitude));
  return <div className="viz-grid"><Chart label="Filtered portfolio action counts" title="Screened actions · displayed assets" data={[{ type: 'bar', x: Object.keys(action), y: Object.values(action), marker: { color: COLORS } }]} layout={{ yaxis: { title: 'Assets' } }}/><Chart label="Filtered portfolio readiness signals" title="Readiness signals · displayed assets" data={[{ type: 'pie', labels: Object.keys(signals), values: Object.values(signals), hole: .55, marker: { colors: COLORS } }]}/><Chart label="Filtered property segments" title="Source segments · displayed assets" data={[{ type: 'bar', x: Object.keys(segments), y: Object.values(segments), marker: { color: '#009d9a' } }]} layout={{ yaxis: { title: 'Assets' } }}/><Chart label="Portfolio supplied coordinates" title={PUBLIC_DEMO ? 'Fictional asset coordinates' : 'Supplied asset coordinates'} data={[{ type: 'scatter', mode: 'markers', x: mapped.map(row => row.longitude), y: mapped.map(row => row.latitude), text: mapped.map(row => row.name), marker: { size: 10, color: '#0f62fe' } }]} layout={{ xaxis: { title: 'Longitude' }, yaxis: { title: 'Latitude' } }}/></div>;
}
export function commonMarketHistory(history: any[]) {
  const series = history.filter(row => /price|rent/i.test(row.measure || '')).map(row => ({
    ...row, observations: (row.observations || []).filter((item: any) => isNumber(item.index) && item.index > 0)
      .map((item: any) => { const quarter = /^(\d{4})[- ]?Q([1-4])$/i.exec(item.period || ''); return { ...item, period: quarter ? `${quarter[1]}-Q${quarter[2]}` : item.period }; })
      .filter((item: any) => /^\d{4}-Q[1-4]$/.test(item.period || '')).sort((a: any, b: any) => a.period.localeCompare(b.period)),
  }));
  if (!series.length || series.some(row => !row.observations.length)) return null;
  const sharedPeriods: string[] = series[0].observations.map((item: any) => item.period)
    .filter((period: string) => series.every(row => row.observations.some((item: any) => item.period === period)));
  if (!sharedPeriods.length) return null;
  const start = sharedPeriods[0], end = sharedPeriods[sharedPeriods.length - 1];
  return { start, end, series: series.map(row => {
    const base = row.observations.find((item: any) => item.period === start).index;
    return { ...row, observations: row.observations.filter((item: any) => item.period >= start && item.period <= end)
      .map((item: any) => ({ ...item, rebased_index: item.index / base * 100 })) };
  }), ticks: sharedPeriods.filter((_, index) => index % Math.max(1, Math.ceil(sharedPeriods.length / 6)) === 0) };
}
export function MarketHistoryCharts({ market }: { market: any }) {
  const history = Array.isArray(market?.history) ? market.history : [];
  if (!history.length) return null;
  const common = commonMarketHistory(history);
  if (!common) return <p>A comparable market-history chart is unavailable because the published series do not share a valid base quarter.</p>;
  return <><p>All national price and rent series use the same displayed period, {common.start} to {common.end}, and the same base quarter: {common.start} = 100. Changes describe national indices, not the fictional assets.</p><div className="viz-grid">{['price', 'rent'].map(measure => {
    const series = common.series.filter((row: any) => row.measure?.toLowerCase().includes(measure));
    return <Chart key={measure} label={'Official ' + measure + ' index histories'} title={`National ${measure} indices · ${common.start} = 100`} data={series.map((row: any, index: number) => ({
      type: 'scatter', mode: 'lines', name: row.segment.replaceAll('_', ' '),
      x: row.observations.map((item: any) => item.period), y: row.observations.map((item: any) => item.rebased_index),
      line: { color: COLORS[index % COLORS.length], width: 2 },
    }))} layout={{ yaxis: { title: 'Rebased index', automargin: true }, xaxis: { title: 'Quarter', tickmode: 'array', tickvals: common.ticks, ticktext: common.ticks.map(period => period.replace('-', '<br>')), tickangle: 0, automargin: true }, legend: { orientation: 'h', y: -.27, x: 0 }, margin: { l: 55, r: 15, t: 65, b: 95 } }}/>;
  })}</div></>;
}
export function ZoningCharts({ d }: { d: any }) {
  const c = d.capacity; if (!c) return null;
  const sensitivities = Object.entries(c.sensitivities || {}), nearby = d.surrounding_context?.candidates || [];
  return <div className="viz-grid"><Chart label="Capacity screening quantities" title="Capacity definitions · not additive areas" data={[{ type: 'bar', x: ['Statutory', 'Physical', 'De facto', 'Economic', 'Expected approval'], y: [c.statutory_gfa_sqm, c.physical_gfa_sqm, c.de_facto_gfa_sqm, c.economic_gfa_sqm, c.expected_approved_gfa_sqm], marker: { color: COLORS } }]} layout={{ yaxis: { title: 'GFA sqm' } }}/><Chart label="Marginal capacity sensitivity" title="Finite parameter changes · unstandardised" data={[{ type: 'bar', orientation: 'h', y: sensitivities.map(([name]) => name.replaceAll('_', ' ')), x: sensitivities.map(([, value]) => value), marker: { color: '#009d9a' } }]} layout={{ xaxis: { title: 'Change in expected GFA sqm' } }}/><Chart label="Attainable GFA quantiles" title="Modelled attainable GFA quantiles" data={[{ type: 'bar', x: ['P10', 'P50', 'P90'], y: [c.p10_gfa_sqm, c.p50_gfa_sqm, c.p90_gfa_sqm], marker: { color: COLORS } }]} layout={{ yaxis: { title: 'GFA sqm' } }}/>{nearby.length ? <Chart label="Nearby supplied zoning intensity" title="Surrounding planning context" data={[{ type: 'scatter', mode: 'markers', x: nearby.map((row: any) => row.distance_m), y: nearby.map((row: any) => row.gpr), text: nearby.map((row: any) => row.land_use) }]} layout={{ xaxis: { title: 'Distance m' }, yaxis: { title: 'GPR' } }}/> : <section><h3>Surrounding context unavailable</h3><p>No verified surrounding geometry is present. This does not establish absence of competing supply or clear views.</p></section>}</div>;
}
export function ValuationCharts({ d }: { d: any }) {
  const flows = d.dcf?.cashflows_m || [];
  return <div className="viz-grid"><Chart label="Annual DCF cash flows including exit" title="Annual cash flows · terminal receipt included" data={[{ type: 'bar', x: flows.map((_: any, index: number) => 'Year ' + (index + 1)), y: flows, marker: { color: '#0f62fe' } }]} layout={{ yaxis: { title: 'Undiscounted SGD m' } }}/><Chart label="Current value versus DCF" title="Current input value versus DCF" data={[{ type: 'bar', x: ['Current input value', 'DCF'], y: [d.economics?.current_value_m, d.dcf?.value_m], marker: { color: COLORS } }]} layout={{ yaxis: { title: 'SGD m' } }}/></div>;
}
export function ScenarioCharts({ d, api }: { d: any; api: string }) {
  const samples = useData(api + '/assets/' + encodeURIComponent(d.asset_id) + '/scenario-samples'), matrix = useData(api + '/visualisations/scenario-matrix'); const actions = d.actions || [];
  return <><p>Correlations and distributions reflect supplied model assumptions. The distribution display may use fewer draws than the numerical summary.</p><div className="viz-grid">{samples.data?.samples && <Chart label="Action NPV simulated distributions" title="Simulated action distributions" data={Object.entries(samples.data.samples).map(([name, values], index) => ({ type: 'violin', name, y: values, box: { visible: true }, meanline: { visible: true }, line: { color: COLORS[index % COLORS.length] } }))} layout={{ yaxis: { title: 'Incremental NPV SGD m', zeroline: true } }}/>} {matrix.data?.correlation && <Chart label="Assumed scenario factor correlation" title="Input factor correlations · assumptions" data={[{ type: 'heatmap', x: matrix.data.factors, y: matrix.data.factors, z: matrix.data.correlation, zmin: -1, zmax: 1, colorscale: [[0, '#da1e28'], [.5, '#f4f4f4'], [1, '#0f62fe']] }]}/>}<Chart label="Action P10 P50 P90 ranges" title="P10–P90 outcome ranges · median dots" data={[{ type: 'scatter', mode: 'markers', x: actions.map((row: any) => row.action), y: actions.map((row: any) => row.p50_npv_m), error_y: { type: 'data', symmetric: false, array: actions.map((row: any) => row.p90_npv_m - row.p50_npv_m), arrayminus: actions.map((row: any) => row.p50_npv_m - row.p10_npv_m) }, marker: { size: 10, color: '#009d9a' } }]} layout={{ yaxis: { title: 'Incremental NPV SGD m', zeroline: true } }}/><Chart label="Action probability of incremental loss" title="Probability of incremental loss versus Hold" data={[{ type: 'bar', x: actions.map((row: any) => row.action), y: actions.map((row: any) => row.probability_of_loss), marker: { color: '#ff832b' } }]} layout={{ yaxis: { tickformat: '.0%', range: [0, 1] } }}/></div>{(samples.error || matrix.error) && <p>Some supplementary scenario graphics are unavailable.</p>}</>;
}
export function SelectionCharts({ d }: { d: any }) {
  const s = d.selection; if (!s) return null;
  const rows = s.action_comparison || [], opportunity = s.opportunity || {};
  return <div className="viz-grid"><Chart label="Expected NPV and risk-adjusted action scores" title="Action value and risk preference" data={[{ type: 'bar', name: 'Expected incremental NPV', x: rows.map((row: any) => row.action), y: rows.map((row: any) => row.base_action_npv_m), marker: { color: '#0f62fe' } }, { type: 'bar', name: 'Risk-adjusted score', x: rows.map((row: any) => row.action), y: rows.map((row: any) => row.risk_adjusted_score_m), marker: { color: '#009d9a' } }]} layout={{ barmode: 'group', yaxis: { title: 'SGD m', zeroline: true } }}/><Chart label="Action loss CVaR" title="Marginal loss CVaR by action" data={[{ type: 'bar', x: rows.map((row: any) => row.action), y: rows.map((row: any) => row.cvar_95_m), marker: { color: '#da1e28' } }]} layout={{ yaxis: { title: 'SGD m' } }}/><Chart label="Selected action margins and cost allowance" title="Decision margin and cost sensitivity" data={[{ type: 'bar', x: ['Risk-adjusted margin over Hold', 'Margin over runner-up', 'Additional PV cost allowance'], y: [opportunity.risk_adjusted_margin_over_hold_m, opportunity.margin_to_runner_up_m, opportunity.break_even_additional_pv_cost_m], marker: { color: COLORS } }]} layout={{ yaxis: { title: 'SGD m' } }}/></div>;
}
export function ActionsCharts({ d }: { d: any }) {
  const rows = d.actions || [];
  return <div className="viz-grid"><Chart label="Action expected and P10 outcomes" title="Expected versus downside incremental NPV" data={[{ type: 'bar', name: 'Expected', x: rows.map((row: any) => row.action), y: rows.map((row: any) => row.expected_npv_m) }, { type: 'bar', name: 'P10', x: rows.map((row: any) => row.action), y: rows.map((row: any) => row.p10_npv_m) }]} layout={{ barmode: 'group', yaxis: { title: 'SGD m', zeroline: true } }}/><Chart label="Action capital requirement and execution" title="Net capital and execution duration" data={[{ type: 'bar', name: 'Net capital; negative = receipt', x: rows.map((row: any) => row.action), y: rows.map((row: any) => row.capex_m) }, { type: 'scatter', name: 'Execution years', x: rows.map((row: any) => row.action), y: rows.map((row: any) => row.execution_years), yaxis: 'y2', mode: 'lines+markers' }]} layout={{ yaxis: { title: 'SGD m' }, yaxis2: { title: 'Years', overlaying: 'y', side: 'right' } }}/></div>;
}
export function OptimiserCharts({ o }: { o: any }) {
  if (!o?.annual_plan) return null;
  const distribution = counts(o.selections || [], row => row.action), plan = o.annual_plan;
  return <div className="viz-grid"><Chart label="Audited annual funding plan" title="Annual capital plan · receipts are not profit" data={[{ type: 'bar', name: 'Capex', x: plan.map((row: any) => row.year), y: plan.map((row: any) => row.capex_m) }, { type: 'bar', name: 'Sale receipts', x: plan.map((row: any) => row.year), y: plan.map((row: any) => row.capital_released_m) }, { type: 'scatter', name: 'Remaining liquidity', x: plan.map((row: any) => row.year), y: plan.map((row: any) => row.remaining_liquidity_m), mode: 'lines+markers' }]} layout={{ barmode: 'group', xaxis: { title: 'Decision year' }, yaxis: { title: 'SGD m' } }}/><Chart label="Optimised portfolio action mix" title="Constrained action mix" data={[{ type: 'pie', labels: Object.keys(distribution), values: Object.values(distribution), hole: .5, marker: { colors: COLORS } }]}/></div>;
}
export function LegacyCharts({ rows }: { rows: any[] }) {
  const valid = rows.filter(row => isNumber(row.corrected_current));
  return <div className="viz-grid"><Chart label="Legacy scorecard comparison" title="Legacy scorecard · not an investment return" data={[{ type: 'scatter', mode: 'markers', x: valid.map(row => row.corrected_current), y: valid.map(row => row.corrected_future), text: valid.map(row => row.asset_name) }]} layout={{ xaxis: { title: 'Current score', range: [0, 100] }, yaxis: { title: 'Future score', range: [0, 100] } }}/></div>;
}
export function ModelDiagnostics({ api }: { api: string }) {
  const { data, error } = useData(api + '/visualisations/model-diagnostics');
  if (error) return <section><h2>Model diagnostics unavailable</h2><p>{error}</p></section>;
  if (!data) return <p>Loading model diagnostics…</p>;
  const rows = (data.predictions || []).filter((row: any) => isNumber(row.actual_noi_m) && isNumber(row.point));
  if (!rows.length) return <section><h2>No verified forecasting backtest</h2><p>{data.message || data.status || 'No prediction records are available.'} Model files and independently observed outcomes are required to assess forecasting performance.</p></section>;
  const values = [data.noi_forecast?.p10_p90_coverage, data.decision_policy?.economic_action_hit_rate, data.decision_policy?.legacy_management_label_hit_rate];
  const labels = ['P10–P90 coverage', 'Action match', 'Legacy match'];
  const indices = values.map((_, index) => index).filter(index => isNumber(values[index]));
  return <section><h2>{PUBLIC_DEMO ? 'Illustrative diagnostic fixtures' : 'Diagnostic records · verify evidence'}</h2><p>These records do not establish independent forecasting accuracy or investment alpha. Missing performance metrics remain unavailable and are not displayed as zero. {data.status}</p><div className="viz-grid"><Chart label="Illustrative predicted and comparison NOI" title="Diagnostic NOI comparisons · evidence-dependent" data={[{ type: 'scatter', mode: 'markers', x: rows.map((row: any) => row.actual_noi_m), y: rows.map((row: any) => row.point), text: rows.map((row: any) => row.asset_id) }]} layout={{ xaxis: { title: 'Comparison NOI SGD m' }, yaxis: { title: 'Predicted NOI SGD m' } }}/><Chart label="Diagnostic NOI residuals" title="Prediction minus comparison NOI" data={[{ type: 'histogram', x: rows.map((row: any) => row.point - row.actual_noi_m), marker: { color: '#8a3ffc' } }]} layout={{ xaxis: { title: 'SGD m' } }}/>{indices.length > 0 && <Chart label="Available diagnostic rates" title="Reported diagnostic rates · not alpha evidence" data={[{ type: 'bar', x: indices.map(index => labels[index]), y: indices.map(index => values[index]), marker: { color: COLORS } }]} layout={{ yaxis: { tickformat: '.0%', range: [0, 1] } }}/>}</div></section>;
}
export function EvidenceCharts({ d }: { d: any }) {
  const sources = counts(d.source_rows || [], row => row.sheet || 'Unknown');
  const missing = d.selection?.readiness?.missing || [];
  return <div className="viz-grid"><Chart label="Source reference counts" title={PUBLIC_DEMO ? 'Fictional source references' : 'Source references · not financial verification'} data={[{ type: 'bar', x: Object.keys(sources), y: Object.values(sources), marker: { color: '#009d9a' } }]} layout={{ yaxis: { title: 'References' } }}/><section><h3>Underwriting evidence</h3><p>{d.selection?.readiness?.ready ? 'Required evidence gates passed in the supplied records.' : 'Evidence incomplete.'}</p><ul>{missing.map((field: string) => <li key={field}>{field.replaceAll('_', ' ')}</li>)}</ul></section></div>;
}
export function AuditCharts({ d }: { d: any }) {
  const gates = [{ label: 'Source references recorded', ok: !!d.source_rows?.length }, { label: 'Verified underwriting', ok: d.selection?.readiness?.ready === true }, { label: 'Model result available', ok: !!d.actions?.length }, { label: 'Implementation approval evidenced', ok: false }];
  return <div className="viz-grid"><Chart label="Evidence gate status without inferred approval" title="Recorded evidence gates" data={[{ type: 'bar', orientation: 'h', y: gates.map(row => row.label), x: gates.map(row => row.ok ? 1 : 0), text: gates.map(row => row.ok ? 'Recorded' : 'Not evidenced'), marker: { color: gates.map(row => row.ok ? '#009d9a' : '#ff832b') } }]} layout={{ xaxis: { range: [0, 1.2], showticklabels: false } }}/></div>;
}
export function ZoningPredictionOverview({ api }: { api: string }) {
  const { data, error } = useData(api + '/zoning/discrepancy-map');
  if (error) return <section><h2>Zoning challenger unavailable</h2><p>{error}</p></section>;
  if (!data) return <p>Loading zoning diagnostics…</p>;
  const rows = (data.features || []).filter((feature: any) => feature.geometry?.coordinates).map((feature: any) => ({ ...feature.properties, longitude: feature.geometry.coordinates[0], latitude: feature.geometry.coordinates[1] }));
  const confidence = rows.filter((row: any) => isNumber(row.confidence) && isNumber(row.entropy));
  const future = rows.filter((row: any) => isNumber(row.change_probability));
  return <section><h2>Zoning challenger diagnostics</h2><p>Legal planning controls remain authoritative. {PUBLIC_DEMO ? 'Fixture matches and any confidence values are illustrative; no privately trained model is available here.' : 'Verify model training, calibration and input provenance before interpreting confidence.'} Missing probabilities are not zero.</p><div className="viz-grid"><Chart label="Supplied zoning discrepancy locations" title="Discrepancy locations · source context" data={[{ type: 'scatter', mode: 'markers', x: rows.map((row: any) => row.longitude), y: rows.map((row: any) => row.latitude), text: rows.map((row: any) => row.name), marker: { size: 10, color: rows.map((row: any) => row.severity ?? 0), colorscale: 'Viridis' } }]} layout={{ xaxis: { title: 'Longitude' }, yaxis: { title: 'Latitude' } }}/>{confidence.length ? <Chart label="Available challenger confidence and entropy" title="Challenger confidence · evidence-dependent" data={[{ type: 'scatter', mode: 'markers', x: confidence.map((row: any) => row.confidence), y: confidence.map((row: any) => row.entropy) }]} layout={{ xaxis: { title: 'Top-class confidence', tickformat: '.0%' }, yaxis: { title: 'Normalised entropy' } }}/> : <p>No calibrated confidence or entropy values are available.</p>}{future.length ? <Chart label="Available zoning change screening probabilities" title="Change screening · not permission forecast" data={[{ type: 'histogram', x: future.map((row: any) => row.change_probability) }]} layout={{ xaxis: { tickformat: '.0%' } }}/> : <p>Future zoning-change probabilities are not estimated.</p>}</div></section>;
}
export function AdvancedDevelopmentCharts({ data }: { data: any }) {
  const options = data.development_envelope?.options || [], view = data.viewshed || {}, en = data.enbloc || {}, cash = data.redevelopment_cashflow || {};
  const flows = cash.monthly_cashflows_m || [];
  return <div className="viz-grid">{options.length ? <Chart label="Conceptual envelope alternatives" title="Conceptual geometry · surveyed design required" data={[{ type: 'scatter', mode: 'markers+text', x: options.map((row: any) => row.towers), y: options.map((row: any) => row.gross_gfa_sqm), text: options.map((row: any) => row.storeys + ' storeys'), marker: { size: 12, color: '#009d9a' } }]} layout={{ xaxis: { title: 'Towers' }, yaxis: { title: 'GFA sqm' } }}/> : <p>No feasible envelope fits the supplied planning and geometry assumptions.</p>}
    {view.status !== 'unavailable' && view.contributors?.length && view.horizon_angles_deg?.length ? <Chart label="Assumed geometry viewshed obstruction" title="Proxy obstruction angles · unverified geometry" data={[{ type: 'scatterpolar', theta: view.horizon_angles_deg.map((_: any, index: number) => index * 360 / view.horizon_angles_deg.length), r: view.horizon_angles_deg.map((value: number) => Math.max(0, value)), mode: 'lines', line: { color: '#da1e28' } }]}/> : <section><h3>Viewshed unavailable</h3><p>Missing surrounding geometry is not evidence of open views.</p></section>}
    <Chart label="En-bloc residual screening components" title="En-bloc screening · omitted costs require verification" data={[{ type: 'bar', x: ['Gross development value', 'Construction', 'Maximum land value'], y: [en.gross_development_value_m, en.construction_m, en.maximum_land_value_m], marker: { color: COLORS } }]} layout={{ yaxis: { title: 'SGD m' } }}/><Chart label="Monthly redevelopment incremental cash flows versus Hold" title="Expected unlevered cash flows versus Hold" data={[{ type: 'bar', x: flows.map((_: any, index: number) => index), y: flows, marker: { color: flows.map((value: number) => value >= 0 ? '#009d9a' : '#da1e28') } }]} layout={{ xaxis: { title: 'Month' }, yaxis: { title: 'Incremental SGD m', zeroline: true } }}/></div>;
}
export function TwoStageCharts({ twoStage }: { twoStage: any; stability?: any }) {
  const scenarios = twoStage?.recourse || [], distribution = counts(twoStage?.first_stage || [], row => row.action);
  return <div className="viz-grid"><Chart label="First-stage contingent commitment allocation" title="First-stage commitments · execution is contingent" data={[{ type: 'pie', labels: Object.keys(distribution), values: Object.values(distribution), hole: .5, marker: { colors: COLORS } }]}/><Chart label="Scenario execution and Hold fallback counts" title="Scenario execution and cancellations to Hold" data={[{ type: 'bar', name: 'Execute chosen action', x: scenarios.map((row: any) => row.scenario), y: scenarios.map((row: any) => row.executed.length) }, { type: 'bar', name: 'Cancel development; retain Hold', x: scenarios.map((row: any) => row.scenario), y: scenarios.map((row: any) => row.cancelled.length) }]} layout={{ barmode: 'stack', yaxis: { title: 'Assets' } }}/><Chart label="Two-stage joint scenario portfolio NPVs" title="Portfolio recourse payoffs · decision-time value" data={[{ type: 'bar', x: scenarios.map((row: any) => row.scenario), y: scenarios.map((row: any) => row.portfolio_npv_m), marker: { color: '#009d9a' } }]} layout={{ yaxis: { title: 'SGD m', zeroline: true } }}/></div>;
}
export function StabilityCharts({ stability }: { stability: any }) {
  const rows = (stability.assets || []).filter((row: any) => isNumber(row.stability_score)).sort((a: any, b: any) => a.stability_score - b.stability_score);
  return <div className="viz-grid"><Chart label="Assumption perturbation modal action frequencies" title="Modal action frequency · feasible runs only" data={[{ type: 'bar', orientation: 'h', y: rows.map((row: any) => row.asset_id), x: rows.map((row: any) => row.stability_score), text: rows.map((row: any) => row.modal_action || row.robust_action), marker: { color: rows.map((row: any) => row.fragile ? '#ff832b' : '#009d9a') } }]} layout={{ xaxis: { range: [0, 1], tickformat: '.0%' } }}/></div>;
}
export function MarketRegimeCharts({ api }: { api: string }) {
  const { data } = useData(api + '/models/market-scenarios'); const regimes = data?.regimes?.regimes, transition = data?.regimes?.transition;
  if (!regimes?.length) return <section><h2>Market regime calibration</h2><p>No calibrated regime artifact is available. Fallback factor assumptions are not empirical transition probabilities.</p></section>;
  return <section><h2>Loaded regime assumptions</h2><p>Confirm provenance, sample period and calibration status before interpreting these parameters. Factor rates and approval delays use different units.</p><div className="viz-grid"><Chart label="Loaded market regime transition assumptions" title="Loaded regime transition matrix" data={[{ type: 'heatmap', x: regimes.map((row: any) => row.name), y: regimes.map((row: any) => row.name), z: transition, zmin: 0, zmax: 1, colorscale: 'Blues' }]}/><Chart label="Market regime rate factor means" title="Rate factor means" data={regimes.map((row: any) => ({ type: 'bar', name: row.name, x: ['Rent growth', 'Vacancy', 'Cap rate', 'Interest', 'Cost inflation'], y: row.mean?.slice(0, 5) }))} layout={{ barmode: 'group', yaxis: { tickformat: '.0%' } }}/><Chart label="Approval delay by regime" title="Approval delay assumption" data={[{ type: 'bar', x: regimes.map((row: any) => row.name), y: regimes.map((row: any) => row.mean?.[5]) }]} layout={{ yaxis: { title: 'Months' } }}/></div></section>;
}
export function DigitalTwinCharts({ data, assets, environmentId = 'base' }: { data: any; assets?: any[]; environmentId?: string }) {
  const rows = assets || data?.assets || [], environment = data?.environments?.find((row: any) => row.id === environmentId), actions = ['Hold', 'Retrofit', 'Repurpose', 'Redevelop', 'Sell'];
  const distribution = counts(rows, row => row.environments?.[environmentId]?.recommended_action || 'Unavailable');
  const result = (row: any) => row.environments?.[environmentId] || {};
  return <div className="viz-grid"><Chart label="Filtered recommendations in selected environment" title={`${environment?.label || environmentId} · filtered asset recommendations`} data={[{ type: 'bar', x: Object.keys(distribution), y: Object.values(distribution), marker: { color: COLORS } }]} layout={{ yaxis: { title: 'Assets' } }}/><Chart label="Filtered asset P10 to P90 intervals" title={`${environment?.label || environmentId} · modelled P10–P90`} data={[{ type: 'scatter', mode: 'markers', x: rows.map((row: any) => row.asset_id), y: rows.map((row: any) => result(row).expected_npv_m), error_y: { type: 'data', symmetric: false, array: rows.map((row: any) => Math.max(0, result(row).p90_m - result(row).expected_npv_m)), arrayminus: rows.map((row: any) => Math.max(0, result(row).expected_npv_m - result(row).p10_m)) }, marker: { color: '#0f62fe', size: 9 } }]} layout={{ yaxis: { title: 'Incremental NPV SGD m', zeroline: true } }}/><Chart label="Filtered asset actions across environments" title="Same filtered asset set · environment comparison" data={actions.map((action, index) => ({ type: 'bar', name: action, x: (data.environments || []).map((row: any) => row.label), y: (data.environments || []).map((environment: any) => rows.filter((row: any) => row.environments?.[environment.id]?.recommended_action === action).length), marker: { color: COLORS[index] } }))} layout={{ barmode: 'stack', yaxis: { title: 'Assets' } }}/><Chart label="Filtered asset recommendation agreement" title="Agreement across three environments · not confidence" data={[{ type: 'bar', x: rows.map((row: any) => row.asset_id), y: rows.map((row: any) => row.stability_score), marker: { color: rows.map((row: any) => row.fragile ? '#ff832b' : '#009d9a') } }]} layout={{ yaxis: { tickformat: '.0%', range: [0, 1] } }}/></div>;
}
