import sys,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from packages.orchestration.engine import run_portfolio
from packages.legacy.comparison import compare
from packages.optimisation.engine import optimise_portfolio
assets=[];types=['Mixed use','Office','Retail','Logistics','Residential','Hospitality','Office','Retail','Residential','Industrial'];zones=[('COMMERCIAL & RESIDENTIAL',4.2),('COMMERCIAL',5.6),('COMMERCIAL',3.5),('BUSINESS 2',2.5),('RESIDENTIAL',2.8),('HOTEL',3.5),('COMMERCIAL',4.2),('COMMERCIAL',3.0),('RESIDENTIAL',2.1),('BUSINESS 1',2.5)]
for i,(kind,(land,gpr)) in enumerate(zip(types,zones),1):
 aid=f'DEMO-{i:03d}';segments=[kind];assets.append({'asset_id':aid,'name':f'Demo {kind} Asset {i}','country':'Singapore','jurisdiction':'Singapore URA','segments':segments,'address':f'Illustrative Singapore Location {i}','source_records':1,'source_rows':[{'sheet':'Public Demo','row':i+1}],'latitude':1.25+i*.018,'longitude':103.70+i*.025,'synthetic':True,'synthetic_financials':True,'tenure_hint':{'type':'Freehold' if i%3==0 else '99-year leasehold','remaining_years':None if i%3==0 else 68-i,'source':'synthetic demo'},'ura_zoning':{'matches':[{'objectid':900000+i,'lu_desc':land,'gpr':gpr,'gpr_text':str(gpr),'planning_area':'DEMO PLANNING AREA','subzone':f'DEMO SUBZONE {i}','source_vintage':'URA SPACE Master Plan 2025 demo fixture'}],'match_method':'demo_fixture','spatial_review_required':False,'current_statutory_plan':'Master Plan 2025'},'catalogue_details':['Fictional public demonstration asset']})
results=run_portfolio(assets);legacy=[]
for i,a in enumerate(assets):legacy.append({'asset_id':a['asset_id'],'asset_name':a['name'],'financial':55+i*3,'operational':60+i*2,'market':65+i,'sustainability':50+i*2,'published_current':None,'published_future':None,'source':'synthetic public demo','synthetic_extension':True})
comparison=compare(legacy,results,[]);out=ROOT/'data/examples';out.mkdir(parents=True,exist_ok=True);(out/'demo_portfolio.json').write_text(json.dumps(assets,indent=2),encoding='utf-8');(out/'demo_full_model_results.json').write_text(json.dumps(results,indent=2),encoding='utf-8');(out/'demo_legacy_comparison.json').write_text(json.dumps(comparison,indent=2),encoding='utf-8');market={'as_of':'2026-06-30','status':'synthetic_demo_context','land_use_allocation_hectares':{'Total':73800,'Housing':10400,'Industry And Commerce':9100,'Parks And Nature Reserves':6900},'market_indicators':{'private_residential':{'price_qoq':.005},'office':{'price_qoq':.046,'rent_qoq':.001},'retail':{'price_qoq':.008,'rent_qoq':-.004},'industrial':{'price_qoq':.006}},'warning':'Public demo snapshot. Refresh official sources for current analysis.'};(out/'demo_market_snapshot.json').write_text(json.dumps(market,indent=2),encoding='utf-8');actions=[{'asset_id':x['asset_id'],'name':x['name'],'base_noi_m':x['economics']['current_noi_m'],'actions':x['actions']} for x in results];optimisation=optimise_portfolio(actions,300,8,.5,.3,30);pilot={'status':'public_synthetic_demo','warning':'Fictional assets and synthetic financials','assets':results,'optimisation':optimisation};(out/'demo_pilot_model_v2.json').write_text(json.dumps(pilot,indent=2),encoding='utf-8');predictions=[{'asset_id':x['asset_id'],'actual_noi_m':round(x['economics']['current_noi_m']*1.02,3),'point':round(x['economics']['current_noi_m']*1.018,3),'p10':round(x['economics']['current_noi_m']*.98,3),'p50':round(x['economics']['current_noi_m']*1.018,3),'p90':round(x['economics']['current_noi_m']*1.06,3)} for x in results];backtest={'status':'public_synthetic_demo','noi_forecast':{'mae_m':.05,'p10_p90_coverage':.8,'observations':10},'decision_policy':{'economic_action_hit_rate':.6,'legacy_management_label_hit_rate':.3,'observations':10},'predictions':predictions};(out/'demo_backtest_report.json').write_text(json.dumps(backtest,indent=2),encoding='utf-8');registry={'name':'portfolio-forecasting-demo','version':'0.1.0-demo','synthetic_training':True,'data_source':'fictional public demo','metrics':{'noi':backtest['noi_forecast']},'artifacts':[]};(out/'demo_model_registry.json').write_text(json.dumps(registry,indent=2),encoding='utf-8');(out/'demo_full_portfolio_v2.json').write_text(json.dumps({'governance':{'synthetic_model_allowed':True,'observed_assets':0,'proxy_assets':10},'assets':results},indent=2),encoding='utf-8');print(json.dumps({'demo_assets':len(assets),'output':str(out)},indent=2))
