import sys,json,argparse
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from packages.zoning.challenger import predict
from packages.zoning.change_model import predict_change
from packages.zoning.discrepancy import compare_zoning,feature_collection
from packages.zoning.features import feature_record
p=argparse.ArgumentParser();p.add_argument('--portfolio',default='data/processed/full_model_results.json');p.add_argument('--challenger',default='models/zoning-challenger/0.1.0/zoning_challenger.joblib');p.add_argument('--change-model',default='models/zoning-change/0.1.0/rezoning_probability.joblib');p.add_argument('--output',default='data/processed/zoning_predictions.json');a=p.parse_args();portfolio_path=ROOT/a.portfolio;portfolio_path=portfolio_path if portfolio_path.exists() else ROOT/'data/examples/demo_full_model_results.json';assets=json.loads(portfolio_path.read_text());challenger=ROOT/a.challenger;change=ROOT/a.change_model
if not challenger.exists():raise SystemExit('Zoning challenger model not found. Run train_zoning_challenger.py.')
rows=[]
for asset in assets:
 if asset.get('country')!='Singapore':continue
 zone=(asset.get('ura_zoning',{}).get('matches') or [{}])[0];neighbors=asset.get('surrounding_context',{}).get('candidates',[]);segments=' '.join(asset.get('segments',[])).lower();observed='vegetation' if any(x in segments for x in ['park','open space']) else 'road' if 'transport' in segments else 'building';capacity=asset.get('capacity',{});site_area=(capacity.get('statutory_gfa_sqm')/zone.get('gpr')) if zone.get('gpr') else None;footprint=capacity.get('buildable_footprint_sqm');nearest_park=min((x['distance_m'] for x in neighbors if x.get('land_use') in ('PARK','OPEN SPACE')),default=None);nearest_commercial=min((x['distance_m'] for x in neighbors if 'COMMERCIAL' in str(x.get('land_use'))),default=None);external={'observed_lulc':observed,'conservation_status':'Unknown','building_height_m':(capacity.get('storeys_by_height') or 0)*3.6 or None,'building_density':footprint/site_area if footprint and site_area else None,'road_density':.75 if any(x in segments for x in ['commercial','industrial','mall']) else .5,'impervious_fraction':min(.95,(footprint/site_area if footprint and site_area else .45)+.2),'vegetation_fraction':max(.05,1-min(.95,(footprint/site_area if footprint and site_area else .45)+.2)-.1),'water_fraction':.02,'population_density':18000 if 'residential' in segments else 7000,'employment_density':22000 if any(x in segments for x in ['commercial','office','mall']) else 7000,'distance_mrt_m':500,'distance_road_m':60,'distance_park_m':nearest_park,'distance_commercial_m':nearest_commercial};features=feature_record(asset,external,neighbors);features['site_area_sqm']=site_area;prediction=predict(challenger,features);discrepancy=compare_zoning(zone.get('lu_desc'),zone.get('gpr'),prediction,external['observed_lulc'],None);future=predict_change(change,features) if change.exists() else {'status':'not_trained'};rows.append({'asset_id':asset['asset_id'],'name':asset['name'],'latitude':asset.get('latitude'),'longitude':asset.get('longitude'),'legal_land_use':zone.get('lu_desc'),'legal_gpr':zone.get('gpr'),'planning_area':zone.get('planning_area'),'subzone':zone.get('subzone'),'features':features,'feature_quality':'public_spatial_and_asset_proxy','prediction':prediction,'discrepancy':discrepancy,'future_change':future})
out=ROOT/a.output;out.parent.mkdir(parents=True,exist_ok=True);out.write_text(json.dumps(rows,indent=2),encoding='utf-8');(out.with_name('zoning_discrepancy_map.geojson')).write_text(json.dumps(feature_collection([{**x,'severity':x['discrepancy']['severity'],'status':x['discrepancy']['status'],'predicted_core':x['discrepancy']['predicted_core'],'confidence':x['discrepancy']['prediction_confidence'],'entropy':x['discrepancy']['prediction_entropy'],'change_probability':x['future_change'].get('change_probability')} for x in rows]),indent=2),encoding='utf-8');print(json.dumps({'assets':len(rows),'review':sum(x['discrepancy']['status']=='review' for x in rows),'abstained':sum(x['prediction']['core']['abstain'] for x in rows),'output':str(out)},indent=2))
